import Head from 'next/head'
import Link from 'next/link'
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'

// fetching data using getStaticProps
export const getStaticProps = async () => {

  const res = await fetch('https://www.themealdb.com/api/json/v1/1/categories.php')
  const data = await res.json();

  return {
    props: { categories: data.categories }
  }
}

export default function Home({categories}) {
  return (
    <div>
      <Head>
        <title>Maem | Home</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
      </Head>

      <div className="container">
        <span className="badge bg-warning text-dark p-2">All Categories</span>
        <h2 className="mb-4">Menu Enak</h2>
        <div className="row">
        {categories.map(category => (
          <div className="col-6" key={category.idCategory}>
            <div className="card m-2" style={{maxWidth: '540px'}} key={category.idCategory}>
            <div className="row g-0">
              <div className="col-md-4">
                <img src={category.strCategoryThumb} className="card-img-top" alt="..." />
              </div>
              <div className="col-md-8">
                <div className="card-body">
                  <h5>{category.strCategory}</h5>
                  <Link href={"/category/"+category.strCategory} key={category.idCategory}>
                    <a className="btn btn-outline-dark">Pilih</a>
                  </Link>
                </div>
              </div>
            </div>
            </div>
          </div>
        ))}
        </div>
      </div>

    </div>
  )
}
