import React from 'react'
import Link from 'next/link'
import Head from 'next/head'

// to tell nextjs how much html should be build based on data length
export const getStaticPaths = async () => {
    const res = await fetch('https://www.themealdb.com/api/json/v1/1/categories.php')
    const data = await res.json();

    const paths = data.categories.map(category => {
        return {
            params: { name: category.strCategory.toString() }
        }
    })

    return {
        paths,
        fallback: false
    }
}

export const getStaticProps = async (context) => {
    const name = context.params.name
    const res = await fetch('https://www.themealdb.com/api/json/v1/1/filter.php?c='+name)
    const data = await res.json();
  
    return {
      props: { foods: data.meals, path:name }
    }
  }

function categoryDetail({foods, path}) {
    return (
      <>
      <Head>
        <title>Maem | Category</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
      </Head>
        <div className="container">
          <span className="badge bg-warning text-dark p-2">Category {path}</span>
          <h2 className="mb-4">Maem yang mana nih?</h2>
            <div className="row">
            {foods.map(food => (
          <div className="col-6" key={food.idMeal}>
            <div className="card m-2" style={{maxWidth: '440px'}} key={food.idMeal}>
              <img src={food.strMealThumb} className="card-img-top" alt="..." />
              <div className="card-body">
                <h3>{food.strMeal}</h3>
                <Link href={"/meals/"+food.idMeal} key={food.idMeal}>
                  <a className="btn btn-outline-dark w-100">Maem Ini</a>
                </Link>
                {/* <Link href={"/category/"+path+"/"+food.idMeal} key={food.idMeal}>
                  <a className="btn btn-outline-dark w-100">Maem Ini</a>
                </Link> */}
              </div>
            </div>
          </div>
        ))}
            </div>
        </div>
      </>
    )
}

export default categoryDetail